"""Public contracts generated from OpenAPI, with established convenience aliases."""

from typing import Any, TypeAlias

from pydantic import BaseModel, Field

from .contracts import (
    ActionResponse,
    AddonActionPayload,
    AddonListResponse,
    AddonReorderPayload,
    AddonSubpackPayload,
    AddPlayersPayload,
    AddPlayersResponse,
    AddServerBanResponse,
    AllowlistAddPayload,
    AllowlistPlayer,
    AllowlistRemovePayload,
    APIErrorResponse,
    AppCpuPercent,
    AppInfoResponse,
    AppRamMb,
    AuditLogResponse,
    BackupActionPayload,
    BackupFilesResponse,
    BanAddRequest,
    BanInfo,
    BanRemoveRequest,
    BaseApiResponse,
    BodyLogin,
    ChangePasswordPayload,
    CommandPayload,
    ContentListResponse,
    CpuPercent,
    CustomZipsResponse,
    DiskReadKibS,
    DiskWriteKibS,
    ErrorEnvelope,
    FileNamePayload,
    GenerateTokenPayload,
    GetAllowlistResponse,
    GetApplicationHealthResponse,
    GetApplicationMetricsResponse,
    GetPermissionsResponse,
    GetPluginSettingsResponse,
    GetPropertiesResponse,
    GetServerBansResponse,
    GrantType,
    HealthCheck,
    InstallationAcceptedResponse,
    InstallConfirmationResponse,
    InstalledAddon,
    InstalledAddons,
    InstallServerPayload,
    Keep,
    ListAvailableAddonsResponse,
    LogHistoryPage,
    MemoryMb,
    MetricsSample,
    NetRxKibS,
    NetTxKibS,
    PermissionsSetPayload,
    PermissionsUpdateResponse,
    Pid,
    PlayerInfo,
    PlayerListResponse,
    PlayerPermission,
    PlayerPermissionPayload,
    PlayerScanDetails,
    PlayerScanError,
    PluginInfo,
    PluginPagesResponse,
    PluginSettingsPayload,
    PluginStatusesResponse,
    PluginStatusSetPayload,
    ProcessInfo,
    ProfileUpdatePayload,
    PropertiesPayload,
    PruneDownloadsPayload,
    PruneDownloadsResponse,
    RegistrationResponse,
    RemoveServerBanResponse,
    RestartServerResponse,
    RestoreActionPayload,
    Revision,
    ServerMetrics,
    ServerProcessInfoResponse,
    ServerRunningStatusResponse,
    ServerSettingItemPayload,
    ServerSettingsResponse,
    ServersListResponse,
    ServerSummary,
    SetPluginSettingResponse,
    SettingItemResponse,
    SettingsResponse,
    SetupAccountResponse,
    SetupStatusResponse,
    StartServerResponse,
    StopServerResponse,
    Subpack,
    SysCpuPercent,
    SysRamMb,
    SysRamPercent,
    SysRamTotalMb,
    TaskAcceptedResponse,
    TaskSnapshot,
    ThemeListResponse,
    ThemeUpdatePayload,
    ThreadCount,
    TokenResponse,
    TriggerEventPayload,
    TriggerEventResponse,
    UpdateUserRolePayload,
    UptimeSeconds,
    UserLoginPayload,
    UserResponse,
    Uuid,
)

AddonSchemaResponse = InstalledAddon
AddonTypeGroupSchemaResponse = InstalledAddons
AllowlistGetResponse = GetAllowlistResponse
PermissionsGetResponse = GetPermissionsResponse
PropertiesGetResponse = GetPropertiesResponse
ServerSchemaResponse = ServerSummary
BodyApiLoginForAccessTokenAuthTokenPost = BodyLogin
InstallServerResponse: TypeAlias = (
    InstallationAcceptedResponse | InstallConfirmationResponse
)


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


__all__ = [
    "APIErrorResponse",
    "ActionResponse",
    "AddPlayersPayload",
    "AddPlayersResponse",
    "AddServerBanResponse",
    "AddonActionPayload",
    "AddonListResponse",
    "AddonReorderPayload",
    "AddonSchemaResponse",
    "AddonSubpackPayload",
    "AddonTypeGroupSchemaResponse",
    "AllowlistAddPayload",
    "AllowlistGetResponse",
    "AllowlistPlayer",
    "AllowlistRemovePayload",
    "AppCpuPercent",
    "AppInfoResponse",
    "AppRamMb",
    "AuditLogResponse",
    "BackupActionPayload",
    "BackupFilesResponse",
    "BanAddRequest",
    "BanInfo",
    "BanRemoveRequest",
    "BaseApiResponse",
    "BodyApiLoginForAccessTokenAuthTokenPost",
    "BodyLogin",
    "ChangePasswordPayload",
    "CommandPayload",
    "ContentListResponse",
    "CpuPercent",
    "CustomZipsResponse",
    "DiskReadKibS",
    "DiskWriteKibS",
    "ErrorEnvelope",
    "FileNamePayload",
    "GenerateTokenPayload",
    "GetAllowlistResponse",
    "GetApplicationHealthResponse",
    "GetApplicationMetricsResponse",
    "GetPermissionsResponse",
    "GetPluginSettingsResponse",
    "GetPropertiesResponse",
    "GetServerBansResponse",
    "GrantType",
    "HTTPValidationError",
    "HealthCheck",
    "InstallConfirmationResponse",
    "InstallServerPayload",
    "InstallServerResponse",
    "InstallationAcceptedResponse",
    "InstalledAddon",
    "InstalledAddons",
    "Keep",
    "ListAvailableAddonsResponse",
    "LogHistoryPage",
    "MemoryMb",
    "MetricsSample",
    "NetRxKibS",
    "NetTxKibS",
    "PermissionsGetResponse",
    "PermissionsSetPayload",
    "PermissionsUpdateResponse",
    "Pid",
    "PlayerInfo",
    "PlayerListResponse",
    "PlayerPermission",
    "PlayerPermissionPayload",
    "PlayerScanDetails",
    "PlayerScanError",
    "PluginInfo",
    "PluginPagesResponse",
    "PluginSettingsPayload",
    "PluginStatusSetPayload",
    "PluginStatusesResponse",
    "ProcessInfo",
    "ProfileUpdatePayload",
    "PropertiesGetResponse",
    "PropertiesPayload",
    "PruneDownloadsPayload",
    "PruneDownloadsResponse",
    "RegistrationResponse",
    "RemoveServerBanResponse",
    "RestartServerResponse",
    "RestoreActionPayload",
    "Revision",
    "ServerMetrics",
    "ServerProcessInfoResponse",
    "ServerRunningStatusResponse",
    "ServerSchemaResponse",
    "ServerSettingItemPayload",
    "ServerSettingsResponse",
    "ServerSummary",
    "ServersListResponse",
    "SetPluginSettingResponse",
    "SettingItemResponse",
    "SettingsResponse",
    "SetupAccountResponse",
    "SetupStatusResponse",
    "StartServerResponse",
    "StopServerResponse",
    "Subpack",
    "SysCpuPercent",
    "SysRamMb",
    "SysRamPercent",
    "SysRamTotalMb",
    "TaskAcceptedResponse",
    "TaskSnapshot",
    "ThemeListResponse",
    "ThemeUpdatePayload",
    "ThreadCount",
    "TokenResponse",
    "TriggerEventPayload",
    "TriggerEventResponse",
    "UpdateUserRolePayload",
    "UptimeSeconds",
    "UserLoginPayload",
    "UserResponse",
    "Uuid",
    "ValidationError",
]
