# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-28T22:41:42+00:00

from __future__ import annotations

from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    SecretStr,
)


class ActionResponse(BaseModel):
    status: str | None = Field("success", title="Status")
    message: str = Field(..., title="Message")
    details: Any = Field(None, title="Details")
    task_id: str | None = Field(None, title="Task Id")
    registration_url: str | None = Field(None, title="Registration Url")
    backups: Any = Field(None, title="Backups")


class AddPlayersPayload(BaseModel):
    players: list[str] = Field(
        ...,
        description='List of player strings, e.g., ["PlayerOne:123xuid", "PlayerTwo:456xuid"]',
        title="Players",
    )


class AddPlayersResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    details: dict[str, Any] | None = Field(None, title="Details")
    count: int | None = Field(None, title="Count")


class AddonActionPayload(BaseModel):
    pack_uuid: str = Field(..., description="The UUID of the pack.", title="Pack Uuid")
    pack_type: str = Field(
        ...,
        description="The type of the pack: 'behavior' or 'resource'.",
        title="Pack Type",
    )


class AddonReorderPayload(BaseModel):
    pack_type: str = Field(
        ...,
        description="The type of the pack: 'behavior' or 'resource'.",
        title="Pack Type",
    )
    uuids: list[str] = Field(
        ...,
        description="The exact list of currently active UUIDs in the new desired order.",
        title="Uuids",
    )


class AddonSchemaResponse(BaseModel):
    name: str = Field(..., title="Name")
    uuid: str = Field(..., title="Uuid")
    version: list[int] = Field(..., title="Version")
    status: str = Field(..., title="Status")
    active_subpack: str | None = Field(None, title="Active Subpack")
    path: str | None = Field(None, title="Path")
    icon: str | None = Field(None, title="Icon")
    subpacks: list[dict[str, Any]] | None = Field(None, title="Subpacks")


class AddonSubpackPayload(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    pack_uuid: str = Field(..., description="The UUID of the pack.", title="Pack Uuid")
    pack_type: str = Field(
        ...,
        description="The type of the pack: 'behavior' or 'resource'.",
        title="Pack Type",
    )
    subpack_name: str | None = Field(
        None,
        description="The folder name of the subpack to activate.",
        title="Subpack Name",
    )


class AddonTypeGroupSchemaResponse(BaseModel):
    behavior_packs: list[AddonSchemaResponse] | None = Field(
        None, title="Behavior Packs"
    )
    resource_packs: list[AddonSchemaResponse] | None = Field(
        None, title="Resource Packs"
    )


class AllowlistAddPayload(BaseModel):
    players: list[str] = Field(
        ..., description="List of player gamertags to add.", title="Players"
    )
    ignoresPlayerLimit: bool | None = Field(
        False,
        description="Set 'ignoresPlayerLimit' for these players.",
        title="Ignoresplayerlimit",
    )


class AllowlistGetResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    players: list[dict[str, Any]] = Field(..., title="Players")


class AllowlistRemovePayload(BaseModel):
    players: list[str] = Field(
        ..., description="List of player gamertags to remove.", title="Players"
    )


class AppInfoResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    info: dict[str, Any] | None = Field(None, title="Info")


class AuditLogResponse(BaseModel):
    id: int = Field(..., title="Id")
    user_id: int = Field(..., title="User Id")
    action: str = Field(..., title="Action")
    details: dict[str, Any] | None = Field(None, title="Details")
    timestamp: AwareDatetime = Field(..., title="Timestamp")


class BackupActionPayload(BaseModel):
    backup_type: str = Field(
        ...,
        description="Type of backup: 'world', 'config', or 'all'.",
        title="Backup Type",
    )
    file_to_backup: str | None = Field(
        None,
        description="Name of config file if backup_type is 'config' (e.g., 'server.properties').",
        title="File To Backup",
    )


class BanAddRequest(BaseModel):
    player_name: str = Field(..., title="Player Name")
    xuid: str = Field(..., title="Xuid")
    reason: str | None = Field(None, title="Reason")


class BanRemoveRequest(BaseModel):
    xuid: str = Field(..., title="Xuid")


class BaseApiResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")


class BodyApiLoginForAccessTokenAuthTokenPost(BaseModel):
    remember_me: bool | None = Field(False, title="Remember Me")
    grant_type: str | None = Field(None, title="Grant Type")
    username: str = Field(..., title="Username")
    password: SecretStr = Field(..., title="Password")
    scope: str | None = Field("", title="Scope")
    client_id: str | None = Field(None, title="Client Id")
    client_secret: SecretStr | None = Field(None, title="Client Secret")


class ChangePasswordPayload(BaseModel):
    current_password: str = Field(..., title="Current Password")
    new_password: str = Field(..., title="New Password")


class CommandPayload(BaseModel):
    command: str = Field(
        ..., description="The command to send to the server.", title="Command"
    )


class ContentListResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    files: list[str] | None = Field(None, title="Files")


class CustomZipsResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    custom_zips: list[str] = Field(..., title="Custom Zips")


class FileNamePayload(BaseModel):
    filename: str = Field(..., title="Filename")


class GenerateTokenPayload(BaseModel):
    role: str = Field(..., title="Role")


class InstallServerPayload(BaseModel):
    server_name: str = Field(
        ..., description="Name for the new server.", title="Server Name"
    )
    server_version: str | None = Field(
        "LATEST",
        description="Version to install (e.g., 'LATEST', '1.20.10.01', 'CUSTOM').",
        title="Server Version",
    )
    server_zip_path: str | None = Field(
        None,
        description="Path to a custom ZIP file, if 'CUSTOM' version is selected.",
        title="Server Zip Path",
    )
    overwrite: bool | None = Field(
        False,
        description="If True, confirm overwriting an existing installation.",
        title="Overwrite",
    )


class InstallServerResponse(BaseModel):
    status: str = Field(
        ...,
        description="Status of the installation ('success', 'confirm_needed', 'pending').",
        title="Status",
    )
    message: str = Field(
        ..., description="Descriptive message about the operation.", title="Message"
    )
    server_name: str | None = Field(
        None,
        description="Name of the server, especially if confirmation is needed.",
        title="Server Name",
    )
    task_id: str | None = Field(
        None, description="Task ID for background installation.", title="Task Id"
    )


class PermissionsGetResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    permissions: list[dict[str, Any]] = Field(..., title="Permissions")


class PermissionsUpdateResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    errors: dict[str, str] | None = Field(None, title="Errors")


class PlayerListResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    players: list[dict[str, Any]] | None = Field(None, title="Players")


class PlayerPermissionPayload(BaseModel):
    xuid: str = Field(..., title="Xuid")
    name: str = Field(..., title="Name")
    permission_level: str = Field(..., title="Permission Level")


class PluginPagesResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    pages: list[dict[str, Any]] | None = Field(None, title="Pages")


class PluginStatusSetPayload(BaseModel):
    enabled: bool = Field(
        ...,
        description="Set to true to enable the plugin, false to disable.",
        title="Enabled",
    )


class PluginStatusesResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    plugins: dict[str, dict[str, Any]] | None = Field(None, title="Plugins")


class ProfileUpdatePayload(BaseModel):
    full_name: str = Field(..., title="Full Name")
    email: str = Field(..., title="Email")


class PropertiesGetResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    properties: dict[str, Any] = Field(..., title="Properties")


class PropertiesPayload(BaseModel):
    properties: dict[str, Any] = Field(
        ..., description="Dictionary of properties to set.", title="Properties"
    )


class PruneDownloadsPayload(BaseModel):
    directory: str = Field(
        ...,
        description="The subdirectory within the main download cache to prune (e.g., 'stable' or 'preview').",
        title="Directory",
    )
    keep: int | None = Field(
        None,
        description="Number of most recent files to keep. Defaults to config if omitted.",
        title="Keep",
    )


class PruneDownloadsResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    files_deleted: int | None = Field(None, title="Files Deleted")
    files_kept: int | None = Field(None, title="Files Kept")


class RestoreActionPayload(BaseModel):
    restore_type: str = Field(
        ...,
        description="Type of restore: 'world', 'properties', 'allowlist', 'permissions', or 'all'.",
        title="Restore Type",
    )
    backup_file: str | None = Field(
        None,
        description="Name of the backup file (basename) to restore from (required if not 'all').",
        title="Backup File",
    )


class ServerProcessInfoResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    process_info: dict[str, Any] | None = Field(None, title="Process Info")


class ServerRunningStatusResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    running: bool | None = Field(None, title="Running")


class ServerSchemaResponse(BaseModel):
    name: str = Field(..., title="Name")
    status: str = Field(..., title="Status")
    version: str = Field(..., title="Version")
    player_count: int = Field(..., title="Player Count")
    players: list[dict[str, str]] | None = Field(None, title="Players")


class ServerSettingItemPayload(BaseModel):
    key: str = Field(
        ...,
        description="The dot-notation key of the setting (e.g., 'settings.autoupdate').",
        title="Key",
    )
    value: Any = Field(..., description="The new value for the setting.", title="Value")


class ServerSettingsResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    settings: dict[str, Any] | None = Field(None, title="Settings")
    setting: ServerSettingItemPayload | None = None


class ServersListResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    servers: list[ServerSchemaResponse] | None = Field(None, title="Servers")


class SettingItemResponse(BaseModel):
    key: str = Field(
        ...,
        description="The dot-notation key of the setting (e.g., 'web.port').",
        title="Key",
    )
    value: Any = Field(..., description="The new value for the setting.", title="Value")


class SettingsResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    settings: dict[str, Any] | None = Field(None, title="Settings")
    setting: SettingItemResponse | None = None


class ThemeListResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    themes: list[str] | None = Field(None, title="Themes")


class ThemeUpdatePayload(BaseModel):
    theme: str = Field(..., title="Theme")


class TokenResponse(BaseModel):
    access_token: str = Field(..., title="Access Token")
    token_type: str = Field(..., title="Token Type")
    message: str | None = Field(None, title="Message")


class TriggerEventPayload(BaseModel):
    event_name: str = Field(
        ...,
        description="The namespaced name of the event to trigger (e.g., 'myplugin:myevent').",
        title="Event Name",
    )
    payload: dict[str, Any] | None = Field(
        None, description="Optional dictionary payload for the event.", title="Payload"
    )


class TriggerEventResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    details: dict[str, Any] | None = Field(None, title="Details")


class UpdateUserRolePayload(BaseModel):
    role: str = Field(..., title="Role")


class UserLoginPayload(BaseModel):
    username: str = Field(..., title="Username")
    password: str = Field(..., title="Password")
    remember_me: bool | None = Field(False, title="Remember Me")


class UserResponse(BaseModel):
    id: int = Field(..., title="Id")
    username: str = Field(..., title="Username")
    identity_type: str | None = Field(None, title="Identity Type")
    role: str = Field(..., title="Role")
    is_active: bool = Field(..., title="Is Active")
    theme: str | None = Field("default", title="Theme")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class AddonListResponse(BaseModel):
    status: str = Field(..., title="Status")
    message: str | None = Field(None, title="Message")
    addons: AddonTypeGroupSchemaResponse | None = None


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class PermissionsSetPayload(BaseModel):
    permissions: list[PlayerPermissionPayload] = Field(
        ..., description="List of player permission entries.", title="Permissions"
    )
