# .github/workflows/build-test.yml

name: Build Lint Test

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'src/bsm_api_client/**'
      - 'test/**'
      - 'pyproject.toml'
  pull_request:
    paths:
      - 'src/bsm_api_client/**'
      - 'test/**'
      - 'pyproject.toml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        python-version: ['3.10', '3.13']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -e .[dev]

    - name: Install and run linters
      run: |
        pip install flake8
        flake8 src/bsm_api_client --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501,W503,F541
        flake8 src/bsm_api_client --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=E501,W503,F541

    - name: Run Pytest
      run: |
        python -m pytest